In [413]:
from wget import download
from zipfile import ZipFile
import os

In [414]:
url='https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/python-data-science-aula-1-inicio.zip'
download(url)
local_filename = url.split('/')[-1]
with ZipFile(local_filename, 'r') as myzip:
        myzip.extractall()
os.remove(local_filename)

In [415]:
data_folder = './Python_Data_Science/Numpy/data'

In [416]:
import numpy as np

In [417]:
km = np.loadtxt(data_folder+'/carros-km.txt')

In [418]:
anos = np.loadtxt(data_folder+'/carros-anos.txt', dtype=int)

In [419]:
anos.max()

2019

In [420]:
km_media = km / (anos.max() - anos)

/tmp/ipykernel_284/1548520280.py:1: RuntimeWarning: invalid value encountered in true_divide
  km_media = km / (anos.max() - anos)


In [421]:
type(km_media)

numpy.ndarray

Operacoes Basicas

In [422]:
2+2

4

In [423]:
2-2

0

In [424]:
2*3

6

In [425]:
10/3

3.3333333333333335

In [426]:
10//3

3

In [427]:
2**3

8

In [428]:
10%3

1

In [429]:
10%2

0

In [430]:
5*2+3*2

16

In [431]:
(5*2)+(3*2)

16

In [432]:
5*(2+3)*2

50

In [433]:
_

50

In [434]:
_ + 3 * 2

56

In [435]:
_ / 2

28.0

In [436]:
10 % 2 + 3 // 10

0

In [437]:
5 * (2 + 3) / 2

12.5

In [438]:
2 ** 3 * 4

32

In [439]:
a=2
A=3

a==A

False

In [440]:
ano_atual = 2019
ano_fabricacao = 2003
km_total = 44410.0

In [441]:
km_media = km_total/ (ano_atual-ano_fabricacao)
km_media

2775.625

In [442]:
km_total += 1
km_total

44411.0

In [443]:
ano_atual, ano_fabricacao, km_total = 2019, 2005, 5000.0
km_media = km_total/ (ano_atual-ano_fabricacao)
km_media

357.14285714285717

In [444]:
type(ano_atual)

int

In [445]:
type(km_total)

float

In [446]:
zero_km = True

In [447]:
type(zero_km)

bool

In [448]:
nome = 'Jetta Variant'
nome

'Jetta Variant'

In [449]:
nome = 'Jetta "Variant"'
nome

'Jetta "Variant"'

In [450]:
carro = """
Nome
Marca
Fabricacao
"""

In [451]:
carro

'\nNome\nMarca\nFabricacao\n'

In [452]:
km = None

In [453]:
type(None)

NoneType

In [454]:
a,b,c,d = 10,20,'Python','legal'

In [455]:
a+b

30

In [456]:
str(a)+c

'10Python'

In [457]:
c+d

'Pythonlegal'

In [458]:
float(a)

10.0

In [459]:
ano_atual, ano_fabricacao = 2019, 2019

if ano_atual == ano_fabricacao:
    print(True)
else:
    print(False)

True


In [460]:
#comentario

In [461]:
'''
docstring
'''

'\ndocstring\n'

In [462]:
'oi {}'.format('pessoa')

'oi pessoa'

In [463]:
'Tenho {} {}'.format(30,'anos')

'Tenho 30 anos'

In [464]:
idade = 0.3
texto = 'seculos'
print('Tenho {} {}'.format(idade,texto))

Tenho 0.3 seculos


In [465]:
f'Tenho {idade} {texto}'

'Tenho 0.3 seculos'

In [466]:
Acessorios = ['Roda de liga','Travas eletricas','Piloto automatico','Banco de couro','Ar condicionado','Sensor de estacionamento','Sensor crepuscular','Sensor de chuva']

In [467]:
type(Acessorios)

list

In [468]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]

In [469]:
carros =[Carro_1,Carro_2]
carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

In [470]:
'Roda de liga' in Acessorios

True

In [471]:
'4x4' in Acessorios

False

In [472]:
'Roda de liga' not in Acessorios

False

In [473]:
'4x4' not in Acessorios

True

In [474]:
A = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']
B = ['Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [475]:
A+B

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [476]:
len(Acessorios)

8

In [477]:
Acessorios[0]

'Roda de liga'

In [478]:
Acessorios[1]

'Travas eletricas'

In [479]:
Acessorios[-1]

'Sensor de chuva'

In [480]:
carros[0]

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [481]:
carros[0][0]

'Jetta Variant'

In [482]:
carros[0][-2]

['Rodas de liga', 'Travas elétricas', 'Piloto automático']

In [483]:
carros[0][-2][1]

'Travas elétricas'

In [484]:
Acessorios[2:5]

['Piloto automatico', 'Banco de couro', 'Ar condicionado']

In [485]:
Acessorios[2:]

['Piloto automatico',
 'Banco de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [486]:
Acessorios[:5]

['Roda de liga',
 'Travas eletricas',
 'Piloto automatico',
 'Banco de couro',
 'Ar condicionado']

In [487]:
Acessorios.sort()
Acessorios

['Ar condicionado',
 'Banco de couro',
 'Piloto automatico',
 'Roda de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas eletricas']

In [488]:
Acessorios.append('4x4')
Acessorios

['Ar condicionado',
 'Banco de couro',
 'Piloto automatico',
 'Roda de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas eletricas',
 '4x4']

In [489]:
Acessorios.pop()

'4x4'

In [490]:
Acessorios.pop(3)

'Roda de liga'

In [491]:
Aces = Acessorios.copy()
Aces

['Ar condicionado',
 'Banco de couro',
 'Piloto automatico',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas eletricas']

In [492]:
for item in Acessorios:
    print(item)

Ar condicionado
Banco de couro
Piloto automatico
Sensor crepuscular
Sensor de chuva
Sensor de estacionamento
Travas eletricas


In [493]:
range(10)

range(0, 10)

In [494]:
[*range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [495]:
for i in range(10):
    print(i**2)

0
1
4
9
16
25
36
49
64
81


In [496]:
quadrado = []
for i in range(10):
    quadrado.append(i**2)

quadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [497]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [498]:
for lista in dados:
    print(lista)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento']
['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [499]:
for lista in dados:
    for item in lista:
        print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [500]:
Acessorios = []
for lista in dados:
    for item in lista:
        Acessorios.append(item)

Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

In [501]:
list(set(Acessorios))

['Bancos de couro',
 'Rodas de liga',
 'Sensor de estacionamento',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Freios ABS',
 'Ar condicionado',
 'Controle de estabilidade',
 'Vidros elétricos',
 'Travas elétricas',
 'Câmera de estacionamento',
 '4 X 4',
 'Teto panorâmico',
 'Painel digital',
 'Câmbio automático']

In [502]:
[*set([item for lista in dados for item in lista])]

['Bancos de couro',
 'Rodas de liga',
 'Sensor de estacionamento',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Freios ABS',
 'Ar condicionado',
 'Controle de estabilidade',
 'Vidros elétricos',
 'Travas elétricas',
 'Câmera de estacionamento',
 '4 X 4',
 'Teto panorâmico',
 'Painel digital',
 'Câmbio automático']

In [503]:
dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [504]:
zero_km = []
for lista in dados:
    if(lista[2]):
        zero_km.append(lista)

In [505]:
[lista for lista in dados if(lista[2])]

[['DS5', 2019, True], ['A5', 2019, True]]

In [506]:
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [507]:
print('AND')
print(f'(True and True) o resultado é: {True and True}')
print(f'(True and False) o resultado é: {True and False}')
print(f'(False and True) o resultado é: {False and True}')
print(f'(False and False) o resultado é: {False and False}')

AND
(True and True) o resultado é: True
(True and False) o resultado é: False
(False and True) o resultado é: False
(False and False) o resultado é: False


In [508]:
print('OR')
print(f'(True or True) o resultado é: {True or True}')
print(f'(True or False) o resultado é: {True or False}')
print(f'(False or True) o resultado é: {False or True}')
print(f'(False or False) o resultado é: {False or False}')

OR
(True or True) o resultado é: True
(True or False) o resultado é: True
(False or True) o resultado é: True
(False or False) o resultado é: False


In [509]:
A,B,C = [],[],[]

for lista in dados:
    if(lista[1]<=2000):
        A.append(lista)
    elif(lista[1]>2000 and lista[1]<=2010):
        B.append(lista)
    else:
        C.append(lista)

In [510]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [511]:
import numpy as np

In [512]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [513]:
km_np = np.array([100,200,300,400])
km_np

array([100, 200, 300, 400])

In [514]:
data_folder = './Python_Data_Science/Numpy/data'

In [515]:
km = np.loadtxt(data_folder+'/carros-km.txt',dtype=int)

In [516]:
km.shape

(258,)

In [517]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]

In [518]:
Acessorios = np.array(dados)

In [519]:
Acessorios.shape

(3, 8)

In [520]:
%time for x in np.arange(1000000): x**2

CPU times: user 144 ms, sys: 0 ns, total: 144 ms
Wall time: 143 ms


In [521]:
%time t = [x**2 for x in range(1000000)]

CPU times: user 194 ms, sys: 0 ns, total: 194 ms
Wall time: 193 ms


In [522]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [523]:
idade = 2019 - anos

In [524]:
hm_media = km / idade

/tmp/ipykernel_284/2653185971.py:1: RuntimeWarning: invalid value encountered in true_divide
  hm_media = km / idade


In [525]:
dados = np.array([km,anos])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [526]:
km_media = dados[0]/ (2019 - dados[1])

/tmp/ipykernel_284/1481073909.py:1: RuntimeWarning: invalid value encountered in true_divide
  km_media = dados[0]/ (2019 - dados[1])


In [527]:
contador = np.arange(10)
contador[4]

4

In [528]:
dados[1][2]

1990.0

In [529]:
contador[1:4]

array([1, 2, 3])

In [530]:
contador  % 7 == 0

array([ True, False, False, False, False, False, False,  True, False,
       False])

In [531]:
dados.shape

(2, 5)

In [532]:
dados.ndim

2

In [533]:
dados.size

10

In [534]:
dados.dtype

dtype('float64')

In [535]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [536]:
dados.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [537]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

In [538]:
contador.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [539]:
contador.reshape((5,2),order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [540]:
info_carros = km+anos
info_carros

array([46413.,  7703., 39113.,  2019., 27763.])

In [541]:
dados_new = dados.copy()
dados_new.resize((3,5),refcheck=False)
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [542]:
dados_new[2] = dados_new[0]/(2019 - dados_new[1])

/tmp/ipykernel_284/4142340667.py:1: RuntimeWarning: invalid value encountered in true_divide
  dados_new[2] = dados_new[0]/(2019 - dados_new[1])


In [543]:
data_folder = './Python_Data_Science/Numpy/data/'

In [544]:
anos = np.loadtxt(fname = data_folder+"carros-anos.txt", dtype = int)
km = np.loadtxt(fname = data_folder+"carros-km.txt")
valor = np.loadtxt(fname = data_folder+"carros-valor.txt")

In [545]:
anos.shape

(258,)

In [546]:
dataset = np.column_stack((anos,km,valor))

In [547]:
dataset.shape

(258, 3)

In [548]:
np.mean(dataset,axis=0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [549]:
np.mean(dataset[:10],axis=1)

array([44830.54666667, 37954.98      , 37315.05333333, 42189.35666667,
       40125.03333333, 36745.91      , 19488.06666667, 63972.81333333,
       73974.42333333, 38851.83      ])

In [550]:
dataset.sum(axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [551]:
dataset[:3].sum()

360301.74